# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: "Admin", email: "admin@google.com", password: "administrator")
User.create(username: "Demo User 1", email: "demouser1@gmail.com", password: "password")
User.create(username: "Demo User 2", email: "demouser2@gmail.com", password: "password")
User.create(username: "ai_player_0", email: "aiplayer0@gmail.com", password: "password")
User.create(username: "ai_player_1", email: "aiplayer1@gmail.com", password: "password")
User.create(username: "ai_player_2", email: "aiplayer2@gmail.com", password: "password")
User.create(username: "ai_player_3", email: "aiplayer3@gmail.com", password: "password")
User.create(username: "ai_player_4", email: "aiplayer4@gmail.com", password: "password")
User.create(username: "ai_player_5", email: "aiplayer5@gmail.com", password: "password")
User.create(username: "ai_player_6", email: "aiplayer6@gmail.com", password: "password")
User.create(username: "Evans123", email: "evans123@yahoo.com", password: "evans123")
User.create(username: "chessgod123", email: "chessgod123@yahoo.com", password: "chessgod123")
User.create(username: "chessnoob321", email: "chessnoob321@yahoo.com", password: "chessnoob321")
User.create(username: "Chuck_Fess", email: "Chuck_Fess@gmail.com", password: "Chuck_Fess")
User.create(username: "jonesmh", email: "jonesmh@gmail.com", password: "jonesmh")
User.create(username: "hisrook", email: "hisrook@gmail.com", password: "hisrook")
User.create(username: "z49910150", email: "z49910150@gmail.com", password: "z49910150")
User.create(username: "stefmaster", email: "stefmaster@gmail.com", password: "stefmaster")
User.create(username: "Timegod", email: "Timegod@gmail.com", password: "Timegod")
User.create(username: "lifesource", email: "lifesource@gmail.com", password: "lifesource")
User.create(username: "Kusokosla", email: "Kusokosla@gmail.com", password: "Kusokosla")
User.create(username: "sparowe14", email: "sparowe14@gmail.com", password: "sparowe14")
User.create(username: "Blindkingmen3", email: "Blindkingmen3@gmail.com", password: "Blindkingmen3")
User.create(username: "JARANDujo", email: "JARANDujo@gmail.com", password: "JARANDujo")
User.create(username: "BerserkAsIfUWereMad", email: "BerserkAsIfUWereMad@gmail.com", password: "BerserkAsIfUWereMad")
User.create(username: "A_0123456", email: "A_0123456@gmail.com", password: "A_0123456")
User.create(username: "Mrchess78", email: "Mrchess78@gmail.com", password: "Mrchess78")
User.create(username: "TomVas3", email: "TomVas3@gmail.com", password: "TomVas3")

Match.create(black_player_id: 2, white_player_id: 3, match_type: "classical", move_string: "E7-E5 G1-H3 D8-H4 H3-G1 F8-C5 G1-H3")

Forum.create(category: "General Chess Discussion", description: "The place to discuss general chess topics")
Forum.create(category: "Game Analysis", description: "Show your game and analyze it with the community")
Forum.create(category: "Lichess Feedback", description: "Bug reports, feature requests, suggestions")
Forum.create(category: "Off-Topic Discussion", description: "Everything that isn't related to chess")

post = Post.create(title: "2 Hour practice routine, suggestions?", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "tournament policing", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "41 Moves and No Middle Game | 2300-2500 Puzzle?", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "TB Club looking for online competition during club time", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Very low centipawn loss?", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Blitz tourney 90Mins", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Are there any data which way of playing is the best?", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Team tournament battle!", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "1300 players challenge", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "New Chess Variant: ForwardChess", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Registered Lichess users ...", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Accounts", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Streamer Team Battle!", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "How do you invite ...", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Poker", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Sudden 2000 -> 2100 puzzle rating", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Fatigue alters one's perception", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "U1500 Ultrabullet Arena", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Best Chess Books at My Level, if Even Needed", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Premove standing against unexpected reply.", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Cheating Suspect", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Cheating Suspect1", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Ratings system", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "New Chess Variant: Stupidhouse", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Game Studies", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "BULLET TOURNAMENT", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Team Battle for teams U20 Members", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "1.e4 or 1.d4?", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Stream or video", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Points", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Atomic: A rule that should be changed", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Converting Glicko to Elo", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Lichess Chat/Forum/Private messages translator", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Add is typing... to private chat!", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "CONGRATULATIONS MAGNUS", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "New Insane exercises ( by me) for you", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "sHow to download Pgn of a game?", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Lichess Chess Puzzles Database Download", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Is it Possible to Lose a Title?", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "What is the best way to view Variant databases on Lichess?", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "german11", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Has this ever been proposed?", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Should I notation my school chess tournament?", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Simultaneous exhibitons", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "How can stockfish be so outstanding?", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "A free alternative to 'puzzle rush'", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Lichess community", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Atomic Academy: Atomic Training Team", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "A great comeback", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Berserking team", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "[BrowserPlugins] Lichess Blocks Hiding", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Team Tournaments Question", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "My friend s account keep getting close for no obvious reason", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Chess books are obsolete", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Any tips on blindfold chess?", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "4 player chess on lichess", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "шахматы", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "How to increase my rating effectiveley?", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Finally hit 2000 (in bullet) :)", author_id: (11..28).to_a.sample, forum_id: 1)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)

post = Post.create(title: "My greatest positional masterpiece?", author_id: (11..28).to_a.sample, forum_id: 2)
Comment.create(body: "What a game this was! As a low-rated player, getting to actually play such a perfect game was an incredible feeling.", post_id: post.id, author_id: post.author_id)


post = Post.create(title: "confidence interval", author_id: (11..28).to_a.sample, forum_id: 3)
Comment.create(body: "Is it possible to know what glicko's confidence interval is for any of my ratings? I'm just curious as to how quickly glicko starts to trust its numbers, or how far I am away from provisional in some ratings.
    If you can point me to some general information, that would be sufficient.", post_id: post.id, author_id: post.author_id)
post = Post.create(title: "Post the last song you listened to.", author_id: (11..28).to_a.sample, forum_id: 4)
Comment.create(body: "I want to experience new music. This song came on a random radio station I was listening to. Not my usual taste and never heard of the band before (bit before my time) but I like it.", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)
Comment.create(body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco", post_id: post.id, author_id: post.author_id)



Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")

Blog.create(author_id: 1, category: "Chess", title: "Pacey Penguin Proudly Peaks Podium Pinnacle", description: "Starting the Decade with a Bang", body: "With 448 titled players joining the first event of the decade (and 356 playing) it's one of the largest titled events we've had! It wasn't just the size that was impressive though, the performance of one player took centre stage: GM Andrew Tang (@penguingim1), the Penguin. Starting off with a magnificent streak of 11 wins and a performance rating of 3,419 he laid down a serious marker for the rest of the competition. It wasn't all plain sailing though and the lead he achieved was narrow to start with, chased by Dmitry Andreikin (@Vladimirovich9000) and GM Alireza Firouzja (@alireza2003) at the half hour mark.
As the games passed though, the lead became greater, leading GM Sergei Zhigalko (@Zhigalko_Sergei) and GM Nihal Sarin (@nihalsarin2004) by 15 points just before the halfway point. The Penguin, time and again, showcased how he earned his slippery epithet, with escape acts like this one:")


Blog.create(author_id: 1, category: "Chess", title: "The dust settles on the battlefield", description: "Starting the Decade with a Bang", body: "A hush fell as the clock ticked down its final seconds, to the end of the inaugural Lichess Streamer Team Battle, which team would win... well by that point it was quite firmly decided! Congratulations to Crestbook Chess Club led by GM Sergey Shipov on their impressive performance and victory. It's not all about the winners though, 9 teams participated with over 5,400 players playing 35,190 games and 2,445,197 moves. Thanks to all the streamers leading their teams onto the battlefield, and to all the players! We've had great feedback on the event already and hope to organise another in the future, which teams will be included? Only time will tell, but for now let's congratulate the teams participating in this event: The final standings were:")

Blog.create(author_id: 1, category: "Chess", title: "Streamer Team Battle!", description: "Whose rallying battle cry will you answer?" , body: "A horn sounds in the distance... a call to arms! This Thursday (9th January) at 19:00 UTC, some of the largest chess streamers around will be clashing head to head in a Team Battle on Lichess - and they need your support! But what is a Team Battle?

You may have already heard about the new feature on Lichess, but in case you haven't:

It's an arena format event - complete with berserking and streaks
You join the Battle under the banner of a specific Team
You play against members of all the other Teams joining - but not against your fellows!
The points of the top performing 20 players from each Team go towards the overall leader-board
This event will be 2 hours long, with a 3+0 time control, starting at 19:00 UTC on the 9th of January. Now for the most important question: whose call to arms will you answer? The participating streamers are below, be sure to join their Team - and then when joining the event, just select that Team.")

Blog.create(author_id: 1, category: "Chess", title: "Titled Arena Announcement", description: "The first Titled Arena of the decade is here", body: "The first Lichess Titled Arena of the decade will be on Wednesday the 15th January at 19:00 UTC!

    The event will as usual be preceded by a bullet 1+0 Warm-up Arena, open to all players with a minimum of 20 rated bullet games. Yes, even you." )
Blog.create(author_id: 1, category: "Chess", title: "Lichess End of Year Update 2019", description: "Thank you all for your support!", body: "It’s been another eventful year for Lichess. We continue to grow in all metrics of activity - average players online, numbers of games played per month, and events held. Along with this, we’ve made significant changes to support the website and ensure our players get the most out of Lichess. As per tradition, we’ve decided to highlight what’s happened this year, and to set the bar for next year.

    ")
Blog.create(author_id: 1, category: "Chess", title: "A new logo for Lichess", description: "A major open-source contribution", body: "They are called Maestro, Fresca, Cardinal, Gioco, Tatiana, Staunty and Dubrovny. You can find them near the bottom of the piece selector. Let us know which one is your favourite!

    There are also some new boards available, and more to come.
    
    We hope you enjoy these new designs as much as we do. As always, have fantastic games!")
Blog.create(author_id: 1, category: "Chess", title: "FIDE: Confidentiality Clauses and Secret Votes", description: "An interview with GM Peter Heine Nielsen", body: "GM Peter Heine Nielsen is a Grandmaster from Denmark who has worked at the very highest level in chess for decades. He played in seven Olympiads for Denmark and won the Danish Championship five times. He may be even better known for his work as a second. He’s worked to help both Viswanathan Anand and Magnus Carlsen prepare for World Championship matches.

    Lichess conducted an interview with Peter via email. Lichess questions are in bold italics.")

Blog.create(author_id: 1, category: "Chess", title: "Firouzja keeps the streak going!", description: "he young Iranian tops the TA with another convincing performance", body: "We were treated to an extra long exhibition of chess skill this month, as the Titled Arena was immediately preceded by agadmator's 500k subscriber celebration tournament. The YouTuber's event was so popular that it pushed Lichess's servers to the max and we had to restart the event! Have no fear though, we were back up and running in short order. Congratulations to agadmator for reaching levels of popularity that challenge our servers, and congratulations to the winners of that event, splitting a $2,000 prize pool (GM Daniel Naroditsky (@RebeccaHarris), GM Oleksandr Bortnyk (@Night-King96), GM Alireza Firouzja (@alireza2003), GM Andrew Tang (@penguingim1) and GM Nikolay Chadaev (@N-Chadaev)). The event was open to all, but titled players quickly dominated the standings - it turns out they are quite good at chess.")

Blog.create(author_id: 1, category: "Announcements", title: "960 Ways to Die in the West", description: "GM Zaven Andriasian takes home the gold!", body: "This September, we were treated to a double-bill of Lichess Titled Arenas, with a 960 variant edition at the unprecedented 3+2 time-control. Players were out in force with 270 participants. GM Andrew Tang (@penguingim1) took an early lead, but it was short lived - protesting on stream that he was only tired and not ill, the penguin was not in his finest form. IM Raunak Sadhwani (@Raunaksadhwani2005) took up the mantle with an impressive start and indeed led the field for over an hour and a half before starting to be pegged back by his opponents.")

Blog.create(author_id: 1, category: "Announcements", title: "Announcing the 2019 Antichess World Championship", description: "It's on its way!", body: "The 2019 Antichess World Championship (ACWC) is going to start on Monday 30th September! Last year, FM Vladica Andrejić (@arimakat) took the trophy home after a tense final match against @Ogul1. Will he keep the Antichess World Champion title, or will someone else take the crown? We'll find out soon...

If you're unfamiliar with Antichess, you can read the rules here: https://lichess.org/variant/antichess")

Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Blog.create(author_id: 1, category: "Announcements", title: "Lorem Ipsum Dolor Sit Amet", description: "Lorem Ipsum Dolor Sit Amet", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")


Blog.create(author_id: 1, category: "Chess", title: "Pacey Penguin Proudly Peaks Podium Pinnacle", description: "Starting the Decade with a Bang", body: "With 448 titled players joining the first event of the decade (and 356 playing) it's one of the largest titled events we've had! It wasn't just the size that was impressive though, the performance of one player took centre stage: GM Andrew Tang (@penguingim1), the Penguin. Starting off with a magnificent streak of 11 wins and a performance rating of 3,419 he laid down a serious marker for the rest of the competition. It wasn't all plain sailing though and the lead he achieved was narrow to start with, chased by Dmitry Andreikin (@Vladimirovich9000) and GM Alireza Firouzja (@alireza2003) at the half hour mark.
As the games passed though, the lead became greater, leading GM Sergei Zhigalko (@Zhigalko_Sergei) and GM Nihal Sarin (@nihalsarin2004) by 15 points just before the halfway point. The Penguin, time and again, showcased how he earned his slippery epithet, with escape acts like this one:")


Blog.create(author_id: 1, category: "Chess", title: "The dust settles on the battlefield", description: "Starting the Decade with a Bang", body: "A hush fell as the clock ticked down its final seconds, to the end of the inaugural Lichess Streamer Team Battle, which team would win... well by that point it was quite firmly decided! Congratulations to Crestbook Chess Club led by GM Sergey Shipov on their impressive performance and victory. It's not all about the winners though, 9 teams participated with over 5,400 players playing 35,190 games and 2,445,197 moves. Thanks to all the streamers leading their teams onto the battlefield, and to all the players! We've had great feedback on the event already and hope to organise another in the future, which teams will be included? Only time will tell, but for now let's congratulate the teams participating in this event: The final standings were:")

Blog.create(author_id: 1, category: "Chess", title: "Streamer Team Battle!", description: "Whose rallying battle cry will you answer?" , body: "A horn sounds in the distance... a call to arms! This Thursday (9th January) at 19:00 UTC, some of the largest chess streamers around will be clashing head to head in a Team Battle on Lichess - and they need your support! But what is a Team Battle?

You may have already heard about the new feature on Lichess, but in case you haven't:

It's an arena format event - complete with berserking and streaks
You join the Battle under the banner of a specific Team
You play against members of all the other Teams joining - but not against your fellows!
The points of the top performing 20 players from each Team go towards the overall leader-board
This event will be 2 hours long, with a 3+0 time control, starting at 19:00 UTC on the 9th of January. Now for the most important question: whose call to arms will you answer? The participating streamers are below, be sure to join their Team - and then when joining the event, just select that Team.")

Blog.create(author_id: 1, category: "Chess", title: "Titled Arena Announcement", description: "The first Titled Arena of the decade is here", body: "The first Lichess Titled Arena of the decade will be on Wednesday the 15th January at 19:00 UTC!

    The event will as usual be preceded by a bullet 1+0 Warm-up Arena, open to all players with a minimum of 20 rated bullet games. Yes, even you." )
Blog.create(author_id: 1, category: "Chess", title: "Lichess End of Year Update 2019", description: "Thank you all for your support!", body: "It’s been another eventful year for Lichess. We continue to grow in all metrics of activity - average players online, numbers of games played per month, and events held. Along with this, we’ve made significant changes to support the website and ensure our players get the most out of Lichess. As per tradition, we’ve decided to highlight what’s happened this year, and to set the bar for next year.

    ")
Blog.create(author_id: 1, category: "Chess", title: "A new logo for Lichess", description: "A major open-source contribution", body: "They are called Maestro, Fresca, Cardinal, Gioco, Tatiana, Staunty and Dubrovny. You can find them near the bottom of the piece selector. Let us know which one is your favourite!

    There are also some new boards available, and more to come.
    
    We hope you enjoy these new designs as much as we do. As always, have fantastic games!")
Blog.create(author_id: 1, category: "Chess", title: "FIDE: Confidentiality Clauses and Secret Votes", description: "An interview with GM Peter Heine Nielsen", body: "GM Peter Heine Nielsen is a Grandmaster from Denmark who has worked at the very highest level in chess for decades. He played in seven Olympiads for Denmark and won the Danish Championship five times. He may be even better known for his work as a second. He’s worked to help both Viswanathan Anand and Magnus Carlsen prepare for World Championship matches.

    Lichess conducted an interview with Peter via email. Lichess questions are in bold italics.")

Blog.create(author_id: 1, category: "Chess", title: "Firouzja keeps the streak going!", description: "he young Iranian tops the TA with another convincing performance", body: "We were treated to an extra long exhibition of chess skill this month, as the Titled Arena was immediately preceded by agadmator's 500k subscriber celebration tournament. The YouTuber's event was so popular that it pushed Lichess's servers to the max and we had to restart the event! Have no fear though, we were back up and running in short order. Congratulations to agadmator for reaching levels of popularity that challenge our servers, and congratulations to the winners of that event, splitting a $2,000 prize pool (GM Daniel Naroditsky (@RebeccaHarris), GM Oleksandr Bortnyk (@Night-King96), GM Alireza Firouzja (@alireza2003), GM Andrew Tang (@penguingim1) and GM Nikolay Chadaev (@N-Chadaev)). The event was open to all, but titled players quickly dominated the standings - it turns out they are quite good at chess.")

Blog.create(author_id: 1, category: "Announcements", title: "960 Ways to Die in the West", description: "GM Zaven Andriasian takes home the gold!", body: "This September, we were treated to a double-bill of Lichess Titled Arenas, with a 960 variant edition at the unprecedented 3+2 time-control. Players were out in force with 270 participants. GM Andrew Tang (@penguingim1) took an early lead, but it was short lived - protesting on stream that he was only tired and not ill, the penguin was not in his finest form. IM Raunak Sadhwani (@Raunaksadhwani2005) took up the mantle with an impressive start and indeed led the field for over an hour and a half before starting to be pegged back by his opponents.")

Blog.create(author_id: 1, category: "Announcements", title: "Announcing the 2019 Antichess World Championship", description: "It's on its way!", body: "The 2019 Antichess World Championship (ACWC) is going to start on Monday 30th September! Last year, FM Vladica Andrejić (@arimakat) took the trophy home after a tense final match against @Ogul1. Will he keep the Antichess World Champion title, or will someone else take the crown? We'll find out soon...

If you're unfamiliar with Antichess, you can read the rules here: https://lichess.org/variant/antichess")